// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaEWrPZjj_xtpc8AM889eY3yjbm5Phe0',
    appId: '1:654477187977:web:f675663bf013084dda5f58',
    messagingSenderId: '654477187977',
    projectId: 'hello-flutter-projects',
    authDomain: 'hello-flutter-projects.firebaseapp.com',
    storageBucket: 'hello-flutter-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60OYj1-Xc-DtI-nHzOw7zvFClP_SJPPE',
    appId: '1:654477187977:android:48512bd4ba351fc8da5f58',
    messagingSenderId: '654477187977',
    projectId: 'hello-flutter-projects',
    storageBucket: 'hello-flutter-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPE9CoVEe1KarD2qU10F-fk4TsJ-Mpi9M',
    appId: '1:654477187977:ios:e7b154cb89685e62da5f58',
    messagingSenderId: '654477187977',
    projectId: 'hello-flutter-projects',
    storageBucket: 'hello-flutter-projects.appspot.com',
    iosClientId: '654477187977-alnhh85a1fads1r7bd1ln0pulsd1127k.apps.googleusercontent.com',
    iosBundleId: 'com.hello.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPE9CoVEe1KarD2qU10F-fk4TsJ-Mpi9M',
    appId: '1:654477187977:ios:ba4af138209d45dada5f58',
    messagingSenderId: '654477187977',
    projectId: 'hello-flutter-projects',
    storageBucket: 'hello-flutter-projects.appspot.com',
    iosClientId: '654477187977-mco3ke7qf0a0mvkkph214cnqcck2uv2d.apps.googleusercontent.com',
    iosBundleId: 'com.hello.hello.RunnerTests',
  );
}
